version: '2'

run:
  timeout: 3m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - ineffassign
    - misspell
    - prealloc
    - gocritic

  settings:
    gocyclo:
      min-complexity: 15

    revive:
      severity: warning

issues:
  max-same-issues: 3
